baseURL = "https://vporoshok.me/"
title = "Где-то на дальнем сервере"
# for smart copyright line, leave this blank and check [params.copyright]
copyright = ""

languageCode = "ru-ru"
defaultContentLanguage = "ru"

theme = "minimo"

paginate = 10
enableGitInfo = true
enableRobotsTXT = true
googleAnalytics = "UA-41042060-2"
metaDataFormat = "yaml"
# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = true
preserveTaxonomyNames = true

[params.info]
    description = "Заметки о программировании и не только"
    title404 = "Страница не найдена"

[params.assets]
    favicon = "favicon.ico"
    gopher = "" # used in 404 template ( Generator: https://gopherize.me )

[params.copyright]
    prefix = ""
    holder = "vporoshok"
    startYear = "2018"
    suffix = ""

[params.settings]
    dateFormat = "2006-01-02"
    listDateFormat = "2006-01-02"
    archiveDateFormat = "02.01"
    hideEntryNavigation = ["page"] # boolean / array of sections
    showReadingTime = true
    taxonomyCloudShuffle = true
    accentColor = "#ffcd00"
    hideMainMenu = false

[params.sidebar]
    enable = true

[params.widgets]
    homepage = ["recent_posts"]
    sidebar = ["about", "social_menu", "sidebar_menu", "taxonomy_cloud"]
    footer = []

[params.social]
    email = "vporoshok@gmail.com"
    github = "vporoshok"
    twitter = "vporoshok"
    telegram = "vporoshok"

[params.comments]
    enable = false

[taxonomies]
    category = "categories"
    tag = "tags"

[sitemap]
    changefreq = "monthly"
    filename = "sitemap.xml"
    priority = 0.5

[blackfriday]
    extensions = ["noEmptyLineBeforeBlock"]
